package cli

import "fmt"

func PrintUsage() {

	fmt.Println("Usage:")
	fmt.Println("    exocomp <ui> [flags]")
	fmt.Println("")
	fmt.Println("Arguments:")
	fmt.Println("    <ui> string            UI type")
	fmt.Println("                           Either of: jsonl, tty, web, webview")
	fmt.Println("")
	fmt.Println("Flags:")
	fmt.Println("")
	fmt.Println("    --name string          LLM agent name")
	fmt.Println("                           (default: \"Peanut Hamper\")")
	fmt.Println("")
	fmt.Println("    --agent string         LLM agent type")
	fmt.Println("                           Either of: architect, coder, planner, summarizer, tester")
	fmt.Println("                           (default: \"planner\")")
	fmt.Println("")
	fmt.Println("    --model string         LLM agent model")
	fmt.Println("                           Examples: qwen3-coder:30b, codestral:22b")
	fmt.Println("                           (default: \"qwen3-coder:30b\")")
	fmt.Println("")
	fmt.Println("    --temperature float    LLM agent sampling temperature (0.1-1.0)")
	fmt.Println("                           Lower = more deterministic, fewer hallucinations")
	fmt.Println("                           Higher = more creative, more hallucinations")
	fmt.Println("                           (default: unset)")
	fmt.Println("")
	fmt.Println("    --prompt string        Initial LLM instructions prompt")
	fmt.Println("                           (default: unset)")
	fmt.Println("")
	fmt.Println("    --sandbox string       Path to sandbox directory")
	fmt.Println("                           (default: current working directory)")
	fmt.Println("")
	fmt.Println("    --url string           OpenAI API endpoint for LLM backend")
	fmt.Println("                           (default: \"http://localhost:11434/v1\")")
	fmt.Println("")
	fmt.Println("Examples:")
	fmt.Println("")
	fmt.Println("    # single-agent mode")
	fmt.Println("    exocomp tty --agent=architect")
	fmt.Println("    exocomp web --agent=architect --model=\"qwen3-coder:30b\" --temperature=\"0.7\";")
	fmt.Println("")
	fmt.Println("    # multi-agent mode")
	fmt.Println("    exocomp tty --agent=planner")
	fmt.Println("    exocomp web --agent=planner --model=\"codestral:22b\" --temperature=\"0.5\";")
	fmt.Println("")

}
