package markdown

import "sort"

var Abbreviations map[string]string = map[string]string{
	"ACL":  "Access Control List",
	"AES":  "Advanced Encryption Standard",
	"AMSI": "Anti Malware Scan Interface",
	"AP":   "Access Point",
	"API":  "Application Programming Interface",
	"APT":  "Advanced Persistent Threat",
	"ARP":  "Address Resolution Protocol",
	"ASN":  "Autonomous System Number",
	"AWS":  "Amazon Web Services",

	"BGP": "Border Gateway Protocol",
	"BND": "Bundesnachrichtendienst",
	"BOF": "Beacon Object File",

	"C2":    "Command and Control",
	"CA":    "Certificate Authority",
	"CAPEC": "Common Attack Pattern Enumeration and Classification",
	"CBC":   "Cipher Block Chaining",
	"CCC":   "Chaos Computer Club",
	"CERT":  "Computer Emergency Response Team",
	"CGo":   "C Bridge for Golang",
	"CIA":   "Central Intelligence Agency",
	"CI/CD": "Continuous Integration and Continuous Deployment",
	"CIDR":  "Classless Inter-Domain Routing",
	"CISA":  "Cybersecurity and Infrastructure Security Agency",
	"CISO":  "Chief Information Security Officer",
	"CKC":   "Cyber Kill Chain",
	"CNC":   "Command and Control",
	"CoW":   "Copy-on-Write",
	"CPU":   "Central Processing Unit",
	"CSP":   "Content Security Policy",
	"CSPM":  "Cloud Security Posture Management",
	"CSRF":  "Cross-Site Request Forgery",
	"CSS":   "Cascading Style Sheets",
	"CTF":   "Capture The Flag",
	"CVE":   "Common Vulnerabilities and Exposures",
	"CVSS":  "Common Vulnerability Scoring System",

	"DA":     "Domain Admin",
	"DAISY":  "Digital Accessible Information System",
	"DC":     "Domain Controller",
	"DDoS":   "Distributed Denial of Service",
	"DEP":    "Data Execution Prevention",
	"DHT":    "Distributed Hash Table",
	"DLL":    "Dynamic Link Library",
	"DHCP":   "Dynamic Host Configuration Protocol",
	"DMARC":  "Domain-based Message Authentication, Reporting, and Conformance",
	"DynDNS": "Dynamic Domain Name System",
	"DNS":    "Domain Name System",
	"DNSSEC": "Domain Name System Security Extensions",
	"DOM":    "Document Object Model",
	"DoS":    "Denial of Service",
	"DSCP":   "Differentiated Services Code Point",

	"eBPF": "Extended Berkeley Packet Filter",
	"EDR":  "Endpoint Detection and Response",
	"EDRM": "Electronic Discovery Reference Model",
	"EoP":  "Elevation of Privilege",
	"EPP":  "Endpoint Protection Platform",
	"ESP":  "Encapsulating Security Payload",

	"FQDN": "Fully Qualified Domain Name",
	"FTP":  "File Transfer Protocol",

	"GRE":  "Generic Routing Encapsulation",
	"GUI":  "Graphical User Interface",
	"GPO":  "Group Policy Object",
	"GPU":  "Graphical Processing Unit",
	"GTK":  "GNOME/GIMP ToolKit",
	"GTK3": "GNOME/GIMP ToolKit Version 3",
	"GTK4": "GNOME/GIMP ToolKit Version 4",

	"HMAC":  "Hash-based Message Authentication Code",
	"HTML":  "Hypertext Markup Language",
	"HTML5": "Hypertext Markup Language Version 5",
	"HTTP":  "Hypertext Transfer Protocol",
	"HTTPS": "Hypertext Transfer Protocol Secure",

	"IAM":       "Identity Access Management",
	"ICMP":      "Internet Control Message Protocol",
	"ICS":       "Intrusion Control System",
	"IDE":       "Integrated Development Environment",
	"IDS":       "Intrusion Detection System",
	"IKE":       "Internet Key Exchange",
	"IMAP":      "Internet Message Access Protocol",
	"IOC":       "Indicator of Compromise",
	"IOA":       "Indicator of Attack",
	"IoT":       "Internet of Things",
	"IP":        "Internet Protocol",
	"IPS":       "Intrusion Prevention System",
	"IPsec":     "Internet Protocol Security",
	"IPv4":      "Internet Protocol Version 4",
	"IPv6":      "Internet Protocol Version 6",
	"IPMI":      "Intelligent Platform Management Interface",
	"IR":        "Incident Response",
	"IRC":       "Internet Relay Chat",
	"ISAKMP":    "Internet Security Association and Key Management Protocol",
	"ISAKMP-SA": "Internet Security Association and Key Management Protocol Security Association",
	"ISP":       "Internet Service Provider",

	"JS":   "JavaScript",
	"JSON": "JavaScript Object Notation",
	"JWT":  "JSON Web Token",

	"LAN":    "Local Area Network",
	"LDAP":   "Lightweight Directory Access Protocol",
	"LLDP":   "Link Layer Discovery Protocol",
	"LFI":    "Local File Inclusion",
	"LLM":    "Large Language Model",
	"LOLBAS": "Living Off The Land Binaries and Scripts",
	"LOLBIN": "Living Off The Land Binary",
	"LPE":    "Local Privilege Escalation",
	"LSASS":  "Local Security Authority Subsystem Service",

	"MAC":  "Media Access Control",
	"MAN":  "Metropolitan Area Network",
	"MFA":  "Multi-Factor Authentication",
	"MSS":  "Maximum Segment Size",
	"MITM": "Man-in-the-Middle",
	"MOTW": "Mark of the Web",
	"MP3":  "MPEG Format Version 3",

	"NAT":  "Network Address Translation",
	"NDP":  "Neighbor Discovery Protocol",
	"NDR":  "Network Detection and Response",
	"NIC":  "Network Interface Card",
	"NSA":  "National Security Agency",
	"NTLM": "NT LAN Manager",
	"NTP":  "Network Time Protocol",

	"OAST":  "Out-of-Band Application Security Testing",
	"OAuth": "Open Authorization",
	"OCSP":  "Online Certificate Status Protocol",
	"OSCP":  "Offensive Security Certified Professional",
	"OSI":   "Open Systems Interconnection",
	"OSINT": "Open Source Intelligence",
	"OSPF":  "Open Shortest Path First",
	"OUI":   "Organizationally Unique Identifiers",

	"PAM":  "Privileged Access Management",
	"PAT":  "Port Address Translation",
	"PCI":  "Peripheral Component Interconnect",
	"PDF":  "Portable Document Format",
	"PHP":  "PHP Hypertest Preprocessor",
	"PKI":  "Public Key Infrastructure",
	"POP3": "Post Office Protocol Version 3",
	"PoC":  "Proof of Concept",
	"PPTP": "Point-to-Point Tunneling Protocol",
	"PT":   "Penetration Test",

	"QoS": "Quality of Service",

	"RARP": "Reverse Address Resolution Protocol",
	"RAT":  "Remote Access Trojan",
	"RBAC": "Role-Based Access Control",
	"RCE":  "Remote Code Execution",
	"RDP":  "Remote Desktop Protocol",
	"RFI":  "Remote File Inclusion",
	"RIP":  "Routing Information Protocol",
	"RMCP": "Remote Management Control Protocol",
	"ROP":  "Return-Oriented Programming",
	"RPC":  "Remote Procedure Call",
	"RSA":  "Rivest-Shamir-Adleman",
	"RTF":  "Rich Text Format",
	"RTT":  "Round-Trip Time",

	"SAML": "Security Assertion Markup Language",
	"SAST": "Static Application Security Testing",
	"SBOM": "Software Bill of Materials",
	"SFTP": "SSH File Transfer Protocol",
	"SIEM": "Security Information and Event Management",
	"SMB":  "Server Message Block",
	"SMTP": "Simple Mail Transfer Protocol",
	"SNMP": "Simple Network Management Protocol",
	"SOC":  "Security Operations Center",
	"SOAR": "Security Orchestration, Automation, and Response",
	"SPN":  "Service Principal Name",
	"SQLi": "SQL Injection",
	"SRP":  "Software Restriction Policies",
	"SSDP": "Simple Service Discovery Protocol",
	"SSH":  "Secure Shell",
	"SSID": "Service Set Identifier",
	"SSL":  "Secure Sockets Layer",
	"SSO":  "Single Sign-On",
	"SSRF": "Server-Side Request Forgery",
	"STP":  "Spanning Tree Protocol",
	"SYN":  "Synchronize",
	"SQL":  "Structured Query Language",

	"TCP":  "Transmission Control Protocol",
	"TFTP": "Trivial File Transfer Protocol",
	"TLS":  "Transport Layer Security",
	"TPM":  "Trusted Platform Module",
	"TTL":  "Time To Live",
	"TTP":  "Tactics, Techniques, and Procedures",

	"U2F":  "Universal 2nd Factor",
	"UAC":  "User Account Control",
	"UDP":  "User Datagram Protocol",
	"UPN":  "User Principal Name",
	"UPnP": "Universal Plug and Play",
	"URI":  "Uniform Resource Identifier",
	"URL":  "Uniform Resource Locator",
	"USB":  "Universal Serial Bus",

	"VLAN": "Virtual Local Area Network",
	"VDI":  "Virtual Desktop Infrastructure",
	"VM":   "Virtual Machine",
	"VPN":  "Virtual Private Network",

	"WAF":   "Web Application Firewall",
	"WAN":   "Wide Area Network",
	"WCAG":  "Web Content Accessibility Guidelines",
	"WDAC":  "Windows Defender Application Control",
	"WEP":   "Wired Equivalent Privacy",
	"Wi-Fi": "Wireless Fidelity",
	"WLAN":  "Wireless Local Area Network",
	"WMI":   "Windows Management Instrumentation",
	"WPA":   "Wi-Fi Protected Access",
	"WPA2":  "Wi-Fi Protected Access II",
	"WPA3":  "Wi-Fi Protected Access III",
	"WS":    "WebSocket Protocol",
	"WS13":  "WebSocket Version 13 Protocol",
	"WWW":   "World Wide Web",

	"XDR":   "Extended Detection and Response",
	"XHTML": "Extensible Hypertext Markup Language",
	"XML":   "Extensible Markup Language",
	"XSS":   "Cross-Site Scripting",

	"YAML": "Yet Another Markup Language",
	"YARA": "Yet Another Recursive Acronym",
}

var abbreviation_keys []string

func init() {

	abbreviation_keys = make([]string, 0, len(Abbreviations))

	for key, _ := range Abbreviations {
		abbreviation_keys = append(abbreviation_keys, key)
	}

	sort.Slice(abbreviation_keys, func(a int, b int) bool {
		return len(abbreviation_keys[a]) > len(abbreviation_keys[b])
	})

}
